import assert from "node:assert/strict";
import test from "node:test";

import {
  applyActionTitleDatePrefix,
  buildActionOutputUpdates,
  buildWriteNoteContentUpdates,
  formatActionTitleDatePrefix,
  shouldUseChunkedActionInput,
  splitActionContentIntoChunks,
  shouldAutoGenerateActionTitle,
  shouldGenerateTitleForExplicitAction,
  validateActionUpdateResult,
} from "../../src/stores/actionProcessingCore.ts";

test("only default or blank note titles can be auto-generated by actions", () => {
  assert.equal(shouldAutoGenerateActionTitle(""), true);
  assert.equal(shouldAutoGenerateActionTitle("Untitled Note"), true);
  assert.equal(shouldAutoGenerateActionTitle("无标题笔记"), true);
  assert.equal(shouldAutoGenerateActionTitle("未命名筆記"), true);
  assert.equal(shouldAutoGenerateActionTitle("KLC数据来源与飘漆监测"), false);
  assert.equal(shouldAutoGenerateActionTitle("SRP 交流"), false);
});

test("explicit note actions force a title attempt for default titles only", () => {
  assert.equal(shouldGenerateTitleForExplicitAction("无标题笔记"), true);
  assert.equal(shouldGenerateTitleForExplicitAction("Untitled Note"), true);
  assert.equal(shouldGenerateTitleForExplicitAction("AI内容营销与KOC策略同步"), false);
});

test("action generated titles get a note date prefix", () => {
  assert.equal(formatActionTitleDatePrefix("2026-06-04 14:34:57"), "06-04：");
  assert.equal(formatActionTitleDatePrefix("2026-6-4"), "06-04：");
  assert.equal(
    applyActionTitleDatePrefix("AI内容营销与KOC策略同步", "2026-06-04"),
    "06-04： AI内容营销与KOC策略同步"
  );
});

test("action generated title date prefix is not duplicated", () => {
  assert.equal(
    applyActionTitleDatePrefix("06-04： AI内容营销与KOC策略同步", "2026-06-04"),
    "06-04： AI内容营销与KOC策略同步"
  );
  assert.equal(applyActionTitleDatePrefix("", "2026-06-04"), "");
});

test("action output updates can overwrite enhanced content", () => {
  assert.deepEqual(
    buildActionOutputUpdates({
      outputTarget: "enhanced_content",
      writeMode: "overwrite",
      generatedContent: "## Summary\nDone",
      existingContent: "old note",
      existingEnhancedContent: "old enhanced",
      actionPrompt: "Summarize",
      contentHash: "10-abc",
    }),
    {
      enhanced_content: "## Summary\nDone",
      enhancement_prompt: "Summarize",
      enhanced_at_content_hash: "10-abc",
    }
  );
});

test("action output updates append to note content without touching enhanced metadata", () => {
  assert.deepEqual(
    buildActionOutputUpdates({
      outputTarget: "content",
      writeMode: "append",
      generatedContent: "new section\n",
      existingContent: "existing note\n",
      existingEnhancedContent: "existing enhanced",
      actionPrompt: "Append",
      contentHash: "11-def",
    }),
    {
      content: "existing note\n\nnew section",
    }
  );
});

test("action output updates do not overwrite note content with blank generated content", () => {
  assert.deepEqual(
    buildActionOutputUpdates({
      outputTarget: "content",
      writeMode: "overwrite",
      generatedContent: "  \n  ",
      existingContent: "existing note",
      existingEnhancedContent: null,
      actionPrompt: "Summarize",
      contentHash: "13-existing",
    }),
    {}
  );
});

test("chat answer writes append to enhanced content without action metadata", () => {
  assert.deepEqual(
    buildWriteNoteContentUpdates({
      target: "enhanced_content",
      writeMode: "append",
      content: "AI answer",
      existingContent: "existing note",
      existingEnhancedContent: "existing enhanced",
    }),
    {
      enhanced_content: "existing enhanced\n\nAI answer",
    }
  );
});

test("long note action content is split into bounded chunks", () => {
  const content = Array.from(
    { length: 9 },
    (_, index) => `段落${index} ${"内容".repeat(6000)}`
  ).join("\n\n");

  const chunks = splitActionContentIntoChunks(content, 20_000);

  assert.equal(chunks.length > 1, true);
  assert.equal(
    chunks.every((chunk) => chunk.length <= 20_000),
    true
  );
  assert.equal(chunks.join("\n\n").includes("段落8"), true);
});

test("large-context models receive 180k-character note actions directly", () => {
  assert.equal(
    shouldUseChunkedActionInput({
      content: "内容".repeat(92_500),
      contextLength: 262_144,
    }),
    false
  );
});

test("small-context models still use chunked note actions for long transcripts", () => {
  assert.equal(
    shouldUseChunkedActionInput({
      content: "内容".repeat(92_500),
      contextLength: 32_768,
    }),
    true
  );
});

test("unknown-context models try moderately long note actions directly before fallback", () => {
  assert.equal(
    shouldUseChunkedActionInput({
      content: "内容".repeat(92_500),
    }),
    false
  );
});

test("note action writes must fail when the note update did not persist", () => {
  assert.throws(
    () => validateActionUpdateResult({ success: false, error: "no fields" }),
    /Action result was not saved/
  );
  assert.throws(() => validateActionUpdateResult(null), /Action result was not saved/);
  assert.doesNotThrow(() => validateActionUpdateResult({ success: true, note: { id: 1 } }));
});
