import assert from "node:assert/strict";
import test from "node:test";

import {
  buildActionOutputUpdates,
  shouldAutoGenerateActionTitle,
} from "../../src/stores/actionProcessingCore.ts";

test("only default or blank note titles can be auto-generated by actions", () => {
  assert.equal(shouldAutoGenerateActionTitle(""), true);
  assert.equal(shouldAutoGenerateActionTitle("Untitled Note"), true);
  assert.equal(shouldAutoGenerateActionTitle("无标题笔记"), true);
  assert.equal(shouldAutoGenerateActionTitle("未命名筆記"), true);
  assert.equal(shouldAutoGenerateActionTitle("KLC数据来源与飘漆监测"), false);
  assert.equal(shouldAutoGenerateActionTitle("SRP 交流"), false);
});

test("action output updates can overwrite enhanced content", () => {
  assert.deepEqual(
    buildActionOutputUpdates({
      outputTarget: "enhanced_content",
      writeMode: "overwrite",
      generatedContent: "## Summary\nDone",
      existingContent: "old note",
      existingEnhancedContent: "old enhanced",
      actionPrompt: "Summarize",
      contentHash: "10-abc",
    }),
    {
      enhanced_content: "## Summary\nDone",
      enhancement_prompt: "Summarize",
      enhanced_at_content_hash: "10-abc",
    }
  );
});

test("action output updates append to note content without touching enhanced metadata", () => {
  assert.deepEqual(
    buildActionOutputUpdates({
      outputTarget: "content",
      writeMode: "append",
      generatedContent: "new section\n",
      existingContent: "existing note\n",
      existingEnhancedContent: "existing enhanced",
      actionPrompt: "Append",
      contentHash: "11-def",
    }),
    {
      content: "existing note\n\nnew section",
    }
  );
});
