import assert from "node:assert/strict";
import test from "node:test";

import {
  applyActionTitleDatePrefix,
  buildActionOutputUpdates,
  buildWriteNoteContentUpdates,
  formatActionTitleDatePrefix,
  shouldAutoGenerateActionTitle,
} from "../../src/stores/actionProcessingCore.ts";

test("only default or blank note titles can be auto-generated by actions", () => {
  assert.equal(shouldAutoGenerateActionTitle(""), true);
  assert.equal(shouldAutoGenerateActionTitle("Untitled Note"), true);
  assert.equal(shouldAutoGenerateActionTitle("无标题笔记"), true);
  assert.equal(shouldAutoGenerateActionTitle("未命名筆記"), true);
  assert.equal(shouldAutoGenerateActionTitle("KLC数据来源与飘漆监测"), false);
  assert.equal(shouldAutoGenerateActionTitle("SRP 交流"), false);
});

test("action generated titles get a note date prefix", () => {
  assert.equal(formatActionTitleDatePrefix("2026-06-04 14:34:57"), "06-04：");
  assert.equal(formatActionTitleDatePrefix("2026-6-4"), "06-04：");
  assert.equal(
    applyActionTitleDatePrefix("AI内容营销与KOC策略同步", "2026-06-04"),
    "06-04： AI内容营销与KOC策略同步"
  );
});

test("action generated title date prefix is not duplicated", () => {
  assert.equal(
    applyActionTitleDatePrefix("06-04： AI内容营销与KOC策略同步", "2026-06-04"),
    "06-04： AI内容营销与KOC策略同步"
  );
  assert.equal(applyActionTitleDatePrefix("", "2026-06-04"), "");
});

test("action output updates can overwrite enhanced content", () => {
  assert.deepEqual(
    buildActionOutputUpdates({
      outputTarget: "enhanced_content",
      writeMode: "overwrite",
      generatedContent: "## Summary\nDone",
      existingContent: "old note",
      existingEnhancedContent: "old enhanced",
      actionPrompt: "Summarize",
      contentHash: "10-abc",
    }),
    {
      enhanced_content: "## Summary\nDone",
      enhancement_prompt: "Summarize",
      enhanced_at_content_hash: "10-abc",
    }
  );
});

test("action output updates append to note content without touching enhanced metadata", () => {
  assert.deepEqual(
    buildActionOutputUpdates({
      outputTarget: "content",
      writeMode: "append",
      generatedContent: "new section\n",
      existingContent: "existing note\n",
      existingEnhancedContent: "existing enhanced",
      actionPrompt: "Append",
      contentHash: "11-def",
    }),
    {
      content: "existing note\n\nnew section",
    }
  );
});

test("chat answer writes append to enhanced content without action metadata", () => {
  assert.deepEqual(
    buildWriteNoteContentUpdates({
      target: "enhanced_content",
      writeMode: "append",
      content: "AI answer",
      existingContent: "existing note",
      existingEnhancedContent: "existing enhanced",
    }),
    {
      enhanced_content: "existing enhanced\n\nAI answer",
    }
  );
});
